server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  main:
    allow-circular-references: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=5m